name: Continuous Integration
on: 
  push:
    branches:
      - main
  pull_request:                      # Will make the workflow run every time you push to any branch

jobs:
  build-c:
    name: Build and test C#
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Build C#
      run: dotnet build

    - name: Test C#
      run: dotnet test

  build-typescript:
    name: Build and test TypeScript
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4

    - name: Build TypeScript
      run: |
        cd DotnetTemplate.Web
        npm install
        npm run build

    - name: Lint TypeScript
      run: |
        cd DotnetTemplate.Web  
        npm run lint

    - name: Test TypeScript
      run: |
        cd DotnetTemplate.Web  
        npm t

  send-slack-notif:
    name: Sends Slack notification
    runs-on: ubuntu-latest
    needs: [build-c, build-typescript]
    steps:
    
    - name: Send Slack notification
      run: >
        curl -X POST --data-urlencode 'payload={"channel": "#devops-test", "username": "webhookbot", "text": "Worklow completed!"}'' ${{ secrets.SLACK_WEBHOOK_URL }}
