name: Continuous Integration
on: 
  push:
    branches:
      - main
  pull_request:                      # Will make the workflow run every time you push to any branch

jobs:
  build-c:
    name: Build and test C#
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Build C#
      run: dotnet build

    - name: Test C#
      run: dawfjdhaksjdf

  build-typescript:
    name: Build and test TypeScript
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4

    - name: Build TypeScript
      run: |
        cd DotnetTemplate.Web
        npm install
        npm run build

    - name: Lint TypeScript
      run: |
        cd DotnetTemplate.Web  
        npm run lint

    - name: Test TypeScript
      run: |
        cd DotnetTemplate.Web  
        npm t

  send-slack-notif:
    name: Final Step After All Builds
    runs-on: ubuntu-latest
    needs: [build-typescript, build-c]
    if: ${{ always() }}  # 👈 This ensures the job always runs
  
    steps:
      - name: Notify success
        if: ${{ needs.build-typescript.result == 'success' && needs.build-c.result == 'success' }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"channel": "#devops-test", "username": "webhookbot", "text": "✅ All jobs completed successfully!"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
  
      - name: Notify failure
        if: ${{ needs.build-typescript.result == 'failure' || needs.build-c.result == 'failure' }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"channel": "#devops-test", "username": "webhookbot", "text": "❌ One or more jobs failed. Check the logs!"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
  
      - name: Notify cancelled
        if: ${{ needs.build-typescript.result == 'cancelled' || needs.build-c.result == 'cancelled' }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"channel": "#devops-test", "username": "webhookbot", "text": "⚠️ Workflow was cancelled."}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}